name: Backend build

on:
  push:
    branches:
      - 'master'
    workflow_dispatch:

env:
  JAVA_VERSION: 11

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run build
        run: |
          mvn package

      - name: Upload catalog jacoco report for subsequent jobs
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          retention-days: 1
          path: |
            **/target/site/jacoco/jacoco.csv

  generateBadges:
    name: Generate badges
    needs: "build"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download jacoco-report
        uses: actions/download-artifact@v3
        with:
          name: jacoco-report
      - name: Generate catalog code coverage
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: ./target/site/jacoco/jacoco.csv
          coverage-badge-filename: coverage.svg
          coverage-label: "Coverage"
      - name: Commit the badges
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi