name: Backend build

on:
  push:
    branches:
      - 'master'
    workflow_dispatch:

env:
  JAVA_VERSION: 11

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: ${{ env.JAVA_VERSION }}
      # Social media
      - name: Run Social Media build
        run: |
          cd social-media
          mvn package

      - name: Upload social jacoco reports for subsequent jobs
        uses: actions/upload-artifact@v3
        with:
          name: social-media-jacoco-report
          retention-days: 1
          path: |
            social-media/target/site/jacoco/jacoco.csv

      # Bookstore
      - name: Run Bookstore build
        run: |
          cd bookstore
          mvn package

      - name: Upload bookstore jacoco reports for subsequent jobs
        uses: actions/upload-artifact@v3
        with:
          name: bookstore-jacoco-report
          retention-days: 1
          path: |
            bookstore/target/site/jacoco/jacoco.csv

  generateBadges:
    name: Generate badges
    needs: "build"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download social-media-jacoco-report
        uses: actions/download-artifact@v3
        with:
          name: social-media-jacoco-report
      - name: Generate code coverage
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: social-media/social-media/target/site/jacoco/jacoco.csv
          coverage-badge-filename: task3-jr-coverage.svg
          coverage-label: "Social media coverage"
      - name: Download bookstore-jacoco-report
        uses: actions/download-artifact@v3
        with:
          name: bookstore-jacoco-report
      - name: Generate bookstore code coverage
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: ./bookstore/bookstore/target/site/jacoco/jacoco.csv
          coverage-badge-filename: task1-md-coverage.svg
          coverage-label: "Bookstore coverage"
      - name: Commit the badges
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi